from fastapi import APIRouter
from fastapi.responses import FileResponse
from pydantic import BaseModel
from docx import Document
import uuid
import os

router = APIRouter(
    prefix="/export",
    tags=["Export"]
)
class ExportRequest(BaseModel):
    title: str
    content: str

@router.post("/docx")
async def export_docx(request: ExportRequest):

    document = Document()

    title = document.add_heading(
        request.title,
        level=1
    )
    title.style.font.name = "Calibri"

    document.add_paragraph(
        "Generated by ResearchPilot\n"
    )
    document.add_paragraph(
        "---------------------------------------------"
    )
    lines = request.content.split("\n")

    for line in lines:
        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):

            level = line.count("#")
            text = line.replace("#", "").strip()

            if level > 4:
                level = 4
            document.add_heading(
                text,
                level=level
            )

        elif line.startswith("- "):

            document.add_paragraph(
                line[2:],
                style="List Bullet"
            )

        elif line.startswith("|"):

            document.add_paragraph(line)

        else:
            document.add_paragraph(line)

    document.add_page_break()
    document.add_heading(
        "Generated using ResearchPilot",
        level=2
    )

    document.add_paragraph(
        "This report was automatically generated using the ResearchPilot AI Research Assistant."
    )

    filename = f"{uuid.uuid4()}.docx"
    os.makedirs(
        "storage",
        exist_ok=True
    )
    path = os.path.join(
        "storage",
        filename
    )
    document.save(path)

    return FileResponse(
        path,
        filename="ResearchPilot_Report.docx",
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )